import { SafeImage } from '../../core/types'

export const SAFE_EDITORIAL_IMAGE_VAULT: SafeImage[] = [
  // --- TECH & AI (Hardware, Semiconductors, AI Architectures, Servers) ---
  {
    url: 'https://upload.wikimedia.org/wikipedia/commons/0/03/NVIDIA_GPU.jpg',
    source: 'Wikimedia Commons',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:NVIDIA_GPU.jpg',
    author: 'Wikimedia Commons Contributors',
    license: 'CC BY-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    altText: {
      id: 'Papan sirkuit komputasi modern dengan prosesor mikro dan jalur interkoneksi data berkecepatan tinggi',
      en: 'Modern computing circuit board showcasing microprocessors and high-speed data interconnect bus',
      ar: 'لوحة دارات إلكترونية حديثة تعرض معالجات دقيقة ومسارات نقل بيانات فائقة السرعة',
    },
    placement: 'hero',
    tags: [
      'hardware',
      'chip',
      'processor',
      'lpddr6',
      'memory',
      'gpu',
      'semiconductor',
      'motherboard',
      'architecture',
      'blackwell',
      'b200',
    ],
  },
  {
    url: 'https://upload.wikimedia.org/wikipedia/commons/e/ec/Nvidia_A100_SXM4_80GB.jpg',
    source: 'Wikimedia Commons',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Nvidia_A100_SXM4_80GB.jpg',
    author: 'Wikimedia Commons Contributors',
    license: 'CC BY-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    altText: {
      id: 'Unit akselerator komputasi performa tinggi untuk inferensi AI berskala datacenter',
      en: 'High-performance computing accelerator unit engineered for datacenter AI inference',
      ar: 'وحدة تسريع حوسبة عالية الأداء مخصصة لاستدلال الذكاء الاصطناعي في مراكز البيانات',
    },
    placement: 'technical',
    tags: [
      'gpu',
      'nvidia',
      'blackwell',
      'b200',
      'gb200',
      'datacenter',
      'hardware',
      'benchmark',
      'tensor',
      'cooling',
    ],
  },

  // --- ISLAMIC LOGIC & ACADEMIC RESEARCH (Primary-Source Manuscripts, Archaeology) ---
  {
    url: 'https://upload.wikimedia.org/wikipedia/commons/3/37/Birmingham_Quran_manuscript_full.jpg',
    source: 'Cadbury Research Library / University of Birmingham',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Birmingham_Quran_manuscript_full.jpg',
    author: 'Cadbury Research Library',
    license: 'Public domain',
    licenseUrl: 'https://creativecommons.org/publicdomain/mark/1.0/',
    altText: {
      id: 'Lembaran manuskrip kuno dan gulungan naskah perkamen bersejarah beraksara Hijazi',
      en: 'Ancient historical manuscript parchment folios in 7th century Hijazi script',
      ar: 'رقائق مخطوطة قرآنية تاريخية قديمة بالخط الحجازي تعود للقرن السابع الميلادي',
    },
    placement: 'hero',
    tags: [
      'manuscript',
      'birmingham',
      'quran',
      'radiocarbon',
      'hijazi',
      'parchment',
      'archaeology',
      'islamic',
      'epistemology',
    ],
  },
  {
    url: 'https://upload.wikimedia.org/wikipedia/commons/8/87/Persian_Gulf_map.png',
    source: 'Wikimedia Commons',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Persian_Gulf_map.png',
    author: 'Wikimedia Commons Contributors',
    license: 'Public domain',
    licenseUrl: 'https://creativecommons.org/publicdomain/mark/1.0/',
    altText: {
      id: 'Peta geopolitik kawasan Timur Tengah dan Teluk Persia',
      en: 'Geopolitical map of the Middle East and Persian Gulf region',
      ar: 'خريطة جيوسياسية لمنطقة الشرق الأوسط والخليج العربي',
    },
    placement: 'breakdown',
    tags: ['geopolitics', 'iran', 'persian gulf', 'middle east', 'petrodollar', 'hormuz', 'gulf'],
  },
]
