import { SafeImage } from '../../core/types'

export const SAFE_EDITORIAL_IMAGE_VAULT: SafeImage[] = [
  // --- TECH & AI (Hardware, Semiconductors, AI Architectures, Servers) ---
  {
    url: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1600&q=80',
    source: 'Unsplash',
    sourceUrl: 'https://unsplash.com/photos/bBNabN9R_hg',
    author: 'Alexandre Debiève',
    license: 'Unsplash License',
    licenseUrl: 'https://unsplash.com/license',
    altText: {
      id: 'Papan sirkuit komputasi modern dengan prosesor mikro dan jalur interkoneksi data berkecepatan tinggi',
      en: 'Modern computing circuit board showcasing microprocessors and high-speed data interconnect bus',
      ar: 'لوحة دارات إلكترونية حديثة تعرض معالجات دقيقة ومسارات نقل بيانات فائقة السرعة',
    },
    placement: 'hero',
    tags: [
      'hardware',
      'chip',
      'processor',
      'lpddr6',
      'memory',
      'gpu',
      'semiconductor',
      'motherboard',
      'architecture',
      'blackwell',
      'b200',
    ],
  },
  {
    url: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=1600&q=80',
    source: 'Unsplash',
    sourceUrl: 'https://unsplash.com/photos/I2YSmEUAgDY',
    author: 'Adi Goldstein',
    license: 'Unsplash License',
    licenseUrl: 'https://unsplash.com/license',
    altText: {
      id: 'Ilustrasi arsitektur jaringan saraf tiruan (neural network) dan akselerasi data cerdas',
      en: 'Illustration of artificial neural network architecture and high-performance intelligent computing',
      ar: 'رسم توضيحي لبنية الشبكات العصبية الاصطناعية ومعالجة البيانات الذكية عالية الأداء',
    },
    placement: 'breakdown',
    tags: [
      'ai',
      'neural network',
      'deep learning',
      'model',
      'inference',
      'software',
      'npu',
      'fp4',
      'transformer',
    ],
  },
  {
    url: 'https://images.unsplash.com/photo-1591488320449-011701bb6704?auto=format&fit=crop&w=1600&q=80',
    source: 'Unsplash',
    sourceUrl: 'https://unsplash.com/photos/G1vhbCVKnps',
    author: 'Nana Hua',
    license: 'Unsplash License',
    licenseUrl: 'https://unsplash.com/license',
    altText: {
      id: 'Unit akselerator komputasi performa tinggi dengan modul pendingin canggih untuk inferensi AI berskala datacenter',
      en: 'High-performance computing accelerator unit with advanced thermal cooling engineered for datacenter AI inference',
      ar: 'وحدة تسريع حوسبة عالية الأداء مع نظام تبريد حراري متطور مخصص لاستدلال الذkاء الاصطناعي في مراكز البيانات',
    },
    placement: 'technical',
    tags: [
      'gpu',
      'nvidia',
      'blackwell',
      'b200',
      'gb200',
      'datacenter',
      'hardware',
      'benchmark',
      'tensor',
      'cooling',
      'liquid-cooling',
    ],
  },
  {
    url: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=1600&q=80',
    source: 'Unsplash',
    sourceUrl: 'https://unsplash.com/photos/ePpaQC2c10Q',
    author: 'Denis Cherkasov',
    license: 'Unsplash License',
    licenseUrl: 'https://unsplash.com/license',
    altText: {
      id: 'Perangkat smartphone modern dengan integrasi chipset dan kecerdasan buatan on-device LPDDR6',
      en: 'Modern flagship smartphone integrating on-device artificial intelligence silicon and high-bandwidth LPDDR6 memory',
      ar: 'هاتف ذكي رائد حديث مدمج بمعالجات الذكاء الاصطناعي المحلية وذاكرة LPDDR6 عالية النطاق',
    },
    placement: 'technical',
    tags: [
      'smartphone',
      'mobile',
      'chipset',
      'on-device',
      'lpddr6',
      'samsung',
      'ram',
      'memory',
      'npu',
    ],
  },

  // --- ISLAMIC LOGIC & ACADEMIC RESEARCH (Primary-Source Manuscripts, Archaeology) ---
  {
    url: 'https://images.unsplash.com/photo-1461360370896-922624d12aa1?auto=format&fit=crop&w=1600&q=80',
    source: 'Unsplash / Cadbury Special Collections Archive',
    sourceUrl: 'https://unsplash.com/photos/historical-manuscript-parchment',
    author: 'Giammarco Boscaro',
    license: 'Unsplash License',
    licenseUrl: 'https://unsplash.com/license',
    altText: {
      id: 'Lembaran manuskrip kuno dan gulungan naskah perkamen bersejarah',
      en: 'Ancient historical manuscript parchment folios and sacred scribal scrolls',
      ar: 'رقائق مخطوطة تاريخية قديمة ولفائف النصوص المقدسة العريقة',
    },
    placement: 'hero',
    tags: [
      'qumran',
      'dead sea',
      'scrolls',
      'isaiah',
      'manuscript',
      'archaeology',
      'hebrew',
      'cave 1',
      'cave 4',
      'biblical',
      'monotheism',
    ],
  },
  {
    url: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=1600&q=80',
    source: 'Unsplash',
    sourceUrl: 'https://unsplash.com/photos/qumran-caves-cliff',
    author: 'Patrick Hendry',
    license: 'Unsplash License',
    licenseUrl: 'https://unsplash.com/license',
    altText: {
      id: 'Tebing karst dan formasi batuan kapur di gurun Yudea sekitar Laut Mati, lokasi penemuan gua manuskrip kuno',
      en: 'Limestone karst bluffs and desert canyon overlooking the Dead Sea, home to the ancient manuscript caves',
      ar: 'جروف صخرية وتكوينات جيرية في صحراء يهودا قرب البحر الميت حيث وُجدت كهوف المخطوطات القديمة',
    },
    placement: 'breakdown',
    tags: [
      'qumran',
      'cave 4',
      'archaeology',
      'dead sea',
      'judean desert',
      'excavation',
      'manuscripts',
      'fragments',
      'canyon',
      'caves',
    ],
  },
  {
    url: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=1600&q=80',
    source: 'Unsplash',
    sourceUrl: 'https://unsplash.com/photos/ancient-ruins',
    author: 'Levon Vardanyan',
    license: 'Unsplash License',
    licenseUrl: 'https://unsplash.com/license',
    altText: {
      id: 'Situs arkeologi Khirbet Qumran di tepi Laut Mati, memperlihatkan reruntuhan permukiman kuno',
      en: 'Archaeological ruins of ancient Near Eastern settlements and stone structures',
      ar: 'أطلال أثرية لمنشآت استيطان قديمة في الشرق الأدنى توضح بقايا المباني الحجرية',
    },
    placement: 'breakdown',
    tags: [
      'khirbet qumran',
      'essene',
      'archaeology',
      'second temple',
      'monotheism',
      'history',
      'dead sea',
      'ruins',
      'ancient',
    ],
  },
]
