export interface MediaOutlet {
  id: string
  name: string
  language: 'id' | 'en' | 'ar'
  domain: string
  category: 'tech-ai' | 'general-tech' | 'enterprise' | 'gaming-hardware'
  editorialTier: 2
  strength: string
}

export interface PrimarySourceDefinition {
  type:
    | 'whitepaper'
    | 'research-paper'
    | 'official-newsroom'
    | 'standards-body'
    | 'benchmark-lab'
    | 'archive'
  description: string
}

export const PRIMARY_SOURCE_LAYERS: Record<string, PrimarySourceDefinition> = {
  STANDARDS_BODIES: {
    type: 'standards-body',
    description: 'JEDEC, IEEE, 3GPP, Khronos Group, ISO, W3C',
  },
  ACADEMIC_REPOSITORIES: {
    type: 'research-paper',
    description: 'arXiv, IEEE Xplore, ACM Digital Library, Nature, Science, Springer',
  },
  OFFICIAL_NEWSROOMS: {
    type: 'official-newsroom',
    description:
      'NVIDIA Newsroom, AMD Press, Intel Newsroom, Samsung Semiconductor News, Apple Newsroom, TSMC Press Center',
  },
  INDEPENDENT_BENCHMARK_LABS: {
    type: 'benchmark-lab',
    description: 'SemiAnalysis, MLCommons, SPEC, Geekbench Browser, UL Benchmarks',
  },
  HISTORICAL_ARCHIVES: {
    type: 'archive',
    description:
      'Leon Levy Dead Sea Scrolls Digital Library, Cadbury Research Library (Birmingham), Israel Antiquities Authority, Bibliothèque nationale de France',
  },
}

export const MEDIA_SOURCE_POOLS: {
  indonesia: MediaOutlet[]
  globalEnglish: MediaOutlet[]
  arabic: MediaOutlet[]
} = {
  indonesia: [
    {
      id: 'techinAsia-id',
      name: 'Tech in Asia Indonesia',
      language: 'id',
      domain: 'id.techinasia.com',
      category: 'tech-ai',
      editorialTier: 2,
      strength: 'Startup & In-depth Tech Analysis',
    },
    {
      id: 'kumparan-tech',
      name: 'Kumparan Tech',
      language: 'id',
      domain: 'kumparan.com/kumparantech',
      category: 'general-tech',
      editorialTier: 2,
      strength: 'Fast News & Viral Tech Updates',
    },
    {
      id: 'detikinet',
      name: 'Detikinet',
      language: 'id',
      domain: 'inet.detik.com',
      category: 'general-tech',
      editorialTier: 2,
      strength: 'Consumer Gadgets & Breaking Tech',
    },
    {
      id: 'kompas-tekno',
      name: 'Kompas Tekno',
      language: 'id',
      domain: 'tekno.kompas.com',
      category: 'general-tech',
      editorialTier: 2,
      strength: 'Authoritative Tech Journalism',
    },
    {
      id: 'liputan6-tekno',
      name: 'Liputan6 Tekno',
      language: 'id',
      domain: 'liputan6.com/tekno',
      category: 'general-tech',
      editorialTier: 2,
      strength: 'Consumer Tech & Mobile Trends',
    },
    {
      id: 'sindonews-tekno',
      name: 'Sindonews Tekno',
      language: 'id',
      domain: 'tekno.sindonews.com',
      category: 'general-tech',
      editorialTier: 2,
      strength: 'General Tech & Telecommunication',
    },
    {
      id: 'antara-tekno',
      name: 'Antara Tekno',
      language: 'id',
      domain: 'antaranews.com/tekno',
      category: 'general-tech',
      editorialTier: 2,
      strength: 'Official Wire Tech News',
    },
    {
      id: 'merdeka-tekno',
      name: 'Merdeka Teknologi',
      language: 'id',
      domain: 'merdeka.com/teknologi',
      category: 'general-tech',
      editorialTier: 2,
      strength: 'Digital Trends & Applications',
    },
    {
      id: 'viva-tekno',
      name: 'Viva Tekno',
      language: 'id',
      domain: 'viva.co.id/digital/tekno',
      category: 'general-tech',
      editorialTier: 2,
      strength: 'Trending Tech & Gadget Launches',
    },
    {
      id: 'idntimes-tech',
      name: 'IDN Times Tech',
      language: 'id',
      domain: 'idntimes.com/tech',
      category: 'general-tech',
      editorialTier: 2,
      strength: 'Youth & Consumer Tech Life',
    },
    {
      id: 'kaskus-tech',
      name: 'Kaskus Technonews',
      language: 'id',
      domain: 'kaskus.co.id/forum/521',
      category: 'general-tech',
      editorialTier: 2,
      strength: 'Community Tech Discussions',
    },
    {
      id: 'dailysocial',
      name: 'DailySocial.id',
      language: 'id',
      domain: 'dailysocial.id',
      category: 'tech-ai',
      editorialTier: 2,
      strength: 'Digital Ecosystem & Innovation',
    },
    {
      id: 'jagat-review',
      name: 'Jagat Review',
      language: 'id',
      domain: 'jagatreview.com',
      category: 'tech-ai',
      editorialTier: 2,
      strength: 'Deep Hardware Benchmarks & Reviews',
    },
    {
      id: 'selular-id',
      name: 'Selular.ID',
      language: 'id',
      domain: 'selular.id',
      category: 'general-tech',
      editorialTier: 2,
      strength: 'Telecommunications & Mobile Silicon',
    },
    {
      id: 'telset-id',
      name: 'Telset.id',
      language: 'id',
      domain: 'telset.id',
      category: 'general-tech',
      editorialTier: 2,
      strength: 'Smartphone & Gadget Insights',
    },
    {
      id: 'gizmologi',
      name: 'Gizmologi',
      language: 'id',
      domain: 'gizmologi.id',
      category: 'general-tech',
      editorialTier: 2,
      strength: 'Modern Gadgets & Consumer AI',
    },
    {
      id: 'nextren',
      name: 'Nextren / Grid',
      language: 'id',
      domain: 'nextren.grid.id',
      category: 'general-tech',
      editorialTier: 2,
      strength: 'Consumer Tech Explainers',
    },
    {
      id: 'medcom-tekno',
      name: 'Medcom Teknologi',
      language: 'id',
      domain: 'medcom.id/teknologi',
      category: 'general-tech',
      editorialTier: 2,
      strength: 'Policy & Industry Technology',
    },
    {
      id: 'teknologi-id',
      name: 'Teknologi.id',
      language: 'id',
      domain: 'teknologi.id',
      category: 'tech-ai',
      editorialTier: 2,
      strength: 'Emerging Tech & AI Trends',
    },
    {
      id: 'infokomputer',
      name: 'InfoKomputer',
      language: 'id',
      domain: 'infokomputer.grid.id',
      category: 'enterprise',
      editorialTier: 2,
      strength: 'Enterprise IT & Datacenter',
    },
    {
      id: 'pricebook',
      name: 'Pricebook Articles',
      language: 'id',
      domain: 'pricebook.co.id/article',
      category: 'general-tech',
      editorialTier: 2,
      strength: 'Hardware Specs & Market Pricing',
    },
    {
      id: 'trenasia-tech',
      name: 'TrenAsia Tech',
      language: 'id',
      domain: 'trenasia.com/kategori/teknologi',
      category: 'enterprise',
      editorialTier: 2,
      strength: 'Economic & Market Technology',
    },
    {
      id: 'hybrid-co-id',
      name: 'Hybrid.co.id',
      language: 'id',
      domain: 'hybrid.co.id',
      category: 'gaming-hardware',
      editorialTier: 2,
      strength: 'Gaming Tech & Esports Hardware',
    },
    {
      id: 'techverse-id',
      name: 'Techverse.id',
      language: 'id',
      domain: 'techverse.id',
      category: 'tech-ai',
      editorialTier: 2,
      strength: 'Deep Tech & AI Hardware',
    },
    {
      id: 'duniagames-tech',
      name: 'Dunia Games Tech',
      language: 'id',
      domain: 'duniagames.co.id',
      category: 'gaming-hardware',
      editorialTier: 2,
      strength: 'Gaming Silicon & Peripherals',
    },
  ],
  globalEnglish: [
    {
      id: 'techcrunch',
      name: 'TechCrunch',
      language: 'en',
      domain: 'techcrunch.com',
      category: 'tech-ai',
      editorialTier: 2,
      strength: 'Venture & Frontier Tech Intelligence',
    },
    {
      id: 'the-verge',
      name: 'The Verge',
      language: 'en',
      domain: 'theverge.com',
      category: 'general-tech',
      editorialTier: 2,
      strength: 'Consumer Tech & Narrative Journalism',
    },
    {
      id: 'wired',
      name: 'WIRED',
      language: 'en',
      domain: 'wired.com',
      category: 'tech-ai',
      editorialTier: 2,
      strength: 'Long-form Tech Essays & Culture',
    },
    {
      id: 'engadget',
      name: 'Engadget',
      language: 'en',
      domain: 'engadget.com',
      category: 'general-tech',
      editorialTier: 2,
      strength: 'Hardware Reviews & Breaking News',
    },
    {
      id: 'gizmodo',
      name: 'Gizmodo',
      language: 'en',
      domain: 'gizmodo.com',
      category: 'general-tech',
      editorialTier: 2,
      strength: 'Design, Science & Tech Analysis',
    },
    {
      id: 'cnet',
      name: 'CNET',
      language: 'en',
      domain: 'cnet.com',
      category: 'general-tech',
      editorialTier: 2,
      strength: 'Consumer Testing & Product Lab',
    },
    {
      id: 'zdnet',
      name: 'ZDNET',
      language: 'en',
      domain: 'zdnet.com',
      category: 'enterprise',
      editorialTier: 2,
      strength: 'Enterprise IT & Cybersecurity',
    },
    {
      id: 'techradar',
      name: 'TechRadar',
      language: 'en',
      domain: 'techradar.com',
      category: 'general-tech',
      editorialTier: 2,
      strength: 'Hardware Guides & Global Tech Coverage',
    },
    {
      id: 'ars-technica',
      name: 'Ars Technica',
      language: 'en',
      domain: 'arstechnica.com',
      category: 'tech-ai',
      editorialTier: 2,
      strength: 'Deep Architecture & Silicon Deep Dives',
    },
    {
      id: 'tnw',
      name: 'The Next Web (TNW)',
      language: 'en',
      domain: 'thenextweb.com',
      category: 'tech-ai',
      editorialTier: 2,
      strength: 'European & Global AI Innovation',
    },
    {
      id: 'venturebeat',
      name: 'VentureBeat',
      language: 'en',
      domain: 'venturebeat.com',
      category: 'tech-ai',
      editorialTier: 2,
      strength: 'Enterprise AI & Machine Learning',
    },
    {
      id: 'mashable-tech',
      name: 'Mashable Tech',
      language: 'en',
      domain: 'mashable.com/tech',
      category: 'general-tech',
      editorialTier: 2,
      strength: 'Viral Tech & Digital Culture',
    },
    {
      id: 'digital-trends',
      name: 'Digital Trends',
      language: 'en',
      domain: 'digitaltrends.com',
      category: 'general-tech',
      editorialTier: 2,
      strength: 'Emerging Tech & Consumer Labs',
    },
    {
      id: 'toms-hardware',
      name: "Tom's Hardware",
      language: 'en',
      domain: 'tomshardware.com',
      category: 'tech-ai',
      editorialTier: 2,
      strength: 'Rigorous GPU/CPU Silicon Testing',
    },
    {
      id: '9to5mac',
      name: '9to5Mac',
      language: 'en',
      domain: '9to5mac.com',
      category: 'general-tech',
      editorialTier: 2,
      strength: 'Apple Silicon & Ecosystem News',
    },
    {
      id: 'android-central',
      name: 'Android Central',
      language: 'en',
      domain: 'androidcentral.com',
      category: 'general-tech',
      editorialTier: 2,
      strength: 'Android OS & ARM Chipsets',
    },
    {
      id: 'macrumors',
      name: 'MacRumors',
      language: 'en',
      domain: 'macrumors.com',
      category: 'general-tech',
      editorialTier: 2,
      strength: 'Hardware Supply Chain & Patents',
    },
    {
      id: 'anandtech',
      name: 'AnandTech Archive',
      language: 'en',
      domain: 'anandtech.com',
      category: 'tech-ai',
      editorialTier: 2,
      strength: 'Microarchitecture Gold Standard',
    },
    {
      id: 'pcmag',
      name: 'PCMag',
      language: 'en',
      domain: 'pcmag.com',
      category: 'general-tech',
      editorialTier: 2,
      strength: 'Independent Lab Benchmarking',
    },
    {
      id: 'slashgear',
      name: 'SlashGear',
      language: 'en',
      domain: 'slashgear.com',
      category: 'general-tech',
      editorialTier: 2,
      strength: 'Auto Tech & Consumer Electronics',
    },
    {
      id: 'neowin',
      name: 'Neowin',
      language: 'en',
      domain: 'neowin.net',
      category: 'general-tech',
      editorialTier: 2,
      strength: 'Windows & Enterprise Software',
    },
    {
      id: 'gsmarena',
      name: 'GSMArena',
      language: 'en',
      domain: 'gsmarena.com',
      category: 'general-tech',
      editorialTier: 2,
      strength: 'Mobile Chipsets & Battery Benchmarks',
    },
    {
      id: 'techspot',
      name: 'TechSpot',
      language: 'en',
      domain: 'techspot.com',
      category: 'tech-ai',
      editorialTier: 2,
      strength: 'PC Hardware & Driver Analysis',
    },
    {
      id: 'computerworld',
      name: 'Computerworld',
      language: 'en',
      domain: 'computerworld.com',
      category: 'enterprise',
      editorialTier: 2,
      strength: 'Enterprise Infrastructure & Cloud',
    },
    {
      id: 'cio',
      name: 'CIO',
      language: 'en',
      domain: 'cio.com',
      category: 'enterprise',
      editorialTier: 2,
      strength: 'Datacenter Strategy & Tech Leadership',
    },
  ],
  arabic: [
    {
      id: 'aitnews',
      name: 'AITnews — البوابة العربية للأخبار التقنية',
      language: 'ar',
      domain: 'aitnews.com',
      category: 'tech-ai',
      editorialTier: 2,
      strength: 'Pioneer Arab Tech Journalism',
    },
    {
      id: 'tech-voice',
      name: 'Tech Voice — تيك فويس',
      language: 'ar',
      domain: 'tech-voice.net',
      category: 'general-tech',
      editorialTier: 2,
      strength: 'Consumer Tech & Video Reviews',
    },
    {
      id: 'arabian-business-tech',
      name: 'Arabian Business Tech',
      language: 'ar',
      domain: 'arabianbusiness.com/industries/technology',
      category: 'enterprise',
      editorialTier: 2,
      strength: 'Middle East Tech Economy',
    },
    {
      id: 'arageek-tech',
      name: 'Arageek Tech — أراجيك تك',
      language: 'ar',
      domain: 'arageek.com/tech',
      category: 'general-tech',
      editorialTier: 2,
      strength: 'In-Depth Tech Explainers',
    },
    {
      id: 'unlimit-tech',
      name: 'Unlimit Tech — التقنية بلا حدود',
      language: 'ar',
      domain: 'unlimit-tech.com',
      category: 'general-tech',
      editorialTier: 2,
      strength: 'Hardware Teardowns & Gadgets',
    },
    {
      id: 'skynews-arabia-tech',
      name: 'Sky News Arabia Tech',
      language: 'ar',
      domain: 'skynewsarabia.com/technology',
      category: 'general-tech',
      editorialTier: 2,
      strength: 'Global & Regional Tech News',
    },
    {
      id: 'aljazeera-tech',
      name: 'Al Jazeera Tech',
      language: 'ar',
      domain: 'aljazeera.net/tech',
      category: 'tech-ai',
      editorialTier: 2,
      strength: 'In-depth Tech & Geopolitics',
    },
    {
      id: 'alarabiya-tech',
      name: 'Al Arabiya Tech',
      language: 'ar',
      domain: 'alarabiya.net/technology',
      category: 'enterprise',
      editorialTier: 2,
      strength: 'Business & AI Innovations',
    },
    {
      id: 'asharq-tech',
      name: 'Asharq News Tech — الشرق تكنولوجيا',
      language: 'ar',
      domain: 'asharq.com/technology',
      category: 'tech-ai',
      editorialTier: 2,
      strength: 'Financial & Semiconductor Tech',
    },
    {
      id: 'bbc-arabic-tech',
      name: 'BBC Arabic Science & Tech',
      language: 'ar',
      domain: 'bbc.com/arabic/topics/ckdxnw959n7t',
      category: 'tech-ai',
      editorialTier: 2,
      strength: 'Academic & Scientific Rigor',
    },
    {
      id: 'cnn-arabic-tech',
      name: 'CNN Arabic Tech',
      language: 'ar',
      domain: 'arabic.cnn.com/tech',
      category: 'general-tech',
      editorialTier: 2,
      strength: 'Emerging AI & Digital Transformation',
    },
    {
      id: 'rt-arabic-tech',
      name: 'RT Arabic Tech',
      language: 'ar',
      domain: 'arabic.rt.com/it',
      category: 'general-tech',
      editorialTier: 2,
      strength: 'Engineering & Computing Tech',
    },
    {
      id: 'iqraaly-tech',
      name: 'Iqraaly Tech — إقرأ لي',
      language: 'ar',
      domain: 'iqraaly.com',
      category: 'general-tech',
      editorialTier: 2,
      strength: 'Audio & Narrative Tech',
    },
    {
      id: 'raqami-tv',
      name: 'Raqami TV — رقمي تي في',
      language: 'ar',
      domain: 'raqamitv.com',
      category: 'general-tech',
      editorialTier: 2,
      strength: 'Mobile Hardware & Comparisons',
    },
    {
      id: 'saudi-gamer',
      name: 'Saudi Gamer — سعودي جيمر',
      language: 'ar',
      domain: 'saudigamer.com',
      category: 'gaming-hardware',
      editorialTier: 2,
      strength: 'Gaming Silicon & GPU Tech',
    },
    {
      id: 't3-me-arabic',
      name: 'T3 Middle East Arabic',
      language: 'ar',
      domain: 't3me.com/ar',
      category: 'general-tech',
      editorialTier: 2,
      strength: 'Lifestyle & Cutting-edge Tech',
    },
    {
      id: 'sada-elbalad-tech',
      name: 'Sada Elbalad Tech',
      language: 'ar',
      domain: 'elbalad.news/section/135',
      category: 'general-tech',
      editorialTier: 2,
      strength: 'Regional Consumer Technology',
    },
    {
      id: 'youm7-tech',
      name: 'Youm7 Tech — اليوم السابع',
      language: 'ar',
      domain: 'youm7.com/Section/علوم-وتكنولوجيا/328/1',
      category: 'general-tech',
      editorialTier: 2,
      strength: 'Popular Arab Tech News',
    },
    {
      id: 'gulf-tech',
      name: 'Gulf Tech',
      language: 'ar',
      domain: 'gulftech.me',
      category: 'enterprise',
      editorialTier: 2,
      strength: 'GCC Datacenter & Cloud Tech',
    },
    {
      id: 'oman-tech',
      name: 'Oman Tech',
      language: 'ar',
      domain: 'omantech.om',
      category: 'general-tech',
      editorialTier: 2,
      strength: 'Regional Innovation & Telecom',
    },
    {
      id: 'thaqafna-tech',
      name: 'Thaqafna Tech',
      language: 'ar',
      domain: 'thaqafnafsak.com/tech',
      category: 'general-tech',
      editorialTier: 2,
      strength: 'Tech Literacy & How-To',
    },
    {
      id: 'tech-3arabi',
      name: 'Tech 3arabi — تك عربي',
      language: 'ar',
      domain: 'tech3arabi.com',
      category: 'tech-ai',
      editorialTier: 2,
      strength: 'Arab Tech Startup Ecosystem',
    },
    {
      id: 'wamda',
      name: 'Wamda — ومضة',
      language: 'ar',
      domain: 'wamda.com/ar',
      category: 'tech-ai',
      editorialTier: 2,
      strength: 'MENA AI & Tech Entrepreneurship',
    },
    {
      id: 'entrepreneur-ar',
      name: 'Entrepreneur Al Arabiya',
      language: 'ar',
      domain: 'entrepreneur.com/ar',
      category: 'enterprise',
      editorialTier: 2,
      strength: 'Executive Tech & AI Strategy',
    },
    {
      id: 'computerworld-ar',
      name: 'Computer World Arabic',
      language: 'ar',
      domain: 'computerworld.com',
      category: 'enterprise',
      editorialTier: 2,
      strength: 'Enterprise Arab IT Infrastructure',
    },
  ],
}
